export const GameRules = {
  STARTING_COINS: 2,
  STARTING_INFLUENCES: 2,
  COUP_COST: 7,
  FORCED_COUP_COINS: 10,
  ASSASSINATION_COST: 3,
  STEAL_AMOUNT: 2,
  FOREIGN_AID_AMOUNT: 2,
  TAX_AMOUNT: 3,
  CARDS_PER_CHARACTER: 3,
};
