export enum ConnectionState {
  IDLE = 'IDLE',
  DISCOVERING = 'DISCOVERING',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  RECONNECTING = 'RECONNECTING',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
}
